# Travis automatically runs our code. Cool!
language: java
jdk:
    - oraclejdk8
script:
    - 'javac *.java'
    - 'for f in *.class ; do echo $f | sed -e "s/.class//" ; done | xargs java'
notifications:
    # Let's not get emailed about each run, shall we?
    email: false

